### ISSUE TITLE
Problems with roller shutters and F411

### ISSUE THREAD

**Issue by Reyna1d** [angeloxx/homebridge-myhome#1]
Good evening,
Sorry for my English, but I am french.
First, congratulations for your plugin, it is great.
But, I can not use it with my roller shutters.
I have modules F411 to manage them and the management of the estimated position does not work.
My shutter takes 14s to go up or down completely. The configuration of the accessory is as follows:

`{
"accessory": "MHBlind",
"name": "Arrière",
"address": "0/8/4",
"time": 14
},`

Thank you for your work, continue, it's great.

**Comment by angeloxx** [comment]
Hi @Reyna1d, thank you for your feedback.
The estimated position is calculated starting a known position (fully closed at the startup); to keep this information affordable you need to:
- start the homebridge daemon with the shutter fully closed OR
- start the homebridge daemon and after that fully open (or fully close) so the plugin can start from a known position

This information is lost at restart. Remember that it is a (linear) estimate, so it doesn't care about the start delay (eg. if you have a shutter with tilt bar) and the estimate gets worse if you make many small movements. You can compensate the error with the additional property:

- "startDelayMs": <milliseconds>, that means that the shutter takes <milliseconds> milliseconds to start to move
- "timeAdjust": <percent> a (signed) percent adjustment of the movement, that is proportional to the movement, eg. with a value of 5 you say that the traveled time in x seconds is +5%.
