### ISSUE TITLE
MHBlindAdvanced not working, and solution (maybe) :)

### ISSUE THREAD

**Issue by bbruno84** [angeloxx/homebridge-myhome#11]
Hello,
thanks for your work, i really love it! 
Like other users i can't get working the MHBlindAdvanced device, I've tried with a F454 (lastest FW) and MH202 but the frame that you use doesn't work. In your code I've found this: `*#2*%s*#11#1*%d##`
 (mhclient.js line 116). It lacks two 0 in the shutterpriority section. The correct frame should be `*#2*%s*#11#001*%d##` (tested, working). I hope I was helpful

**Comment by angeloxx** [comment]
Thank you for your support!
You're right, I've tested your frame with F459 and MH201 and both devices supports your version so I've updated the driver with this last commit.

Thank you again.
